### ISSUE TITLE
[BUG] ** Windows Server 2019 no boot/error   **

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [GeorgiaCyber/kinetic#18]
**Describe the bug**
The Windows Server 2019 halts at boot manager with hardware error.

**To Reproduce**
1. create Windows Server 2019 instance.  Upon boot, error occurs.

**Expected behavior**
Windows Server 2019 should boot up fully and allow access to OS

**Screenshots**

**Client Configuration (please complete the following information):**
 - OS: Windows Server 2019
 - Interface: Horizon
   - Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
None

**Comment by bitskri3g** [comment]
Resolved by e650768cff1e3f4d93f17b133f407c16f8dac940

kvm.conf was not being loaded since the kvm kernel module was already active once that file was written.  Final reboot after configuration resolves this and related issues.
