### ISSUE TITLE
[FEATURE] Cloud-init supported Security Onion image

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [GeorgiaCyber/kinetic#19]
**Is your feature request related to a problem? Please describe.**
This image is needed to support the GTA training requirements.

**Describe the solution you'd like**
cloud-init capable security-onion iamge

**Describe alternatives you've considered**

**Additional context**

**Comment by bitskri3g** [comment]
Closing this - applies to pillar, not core.

https://github.com/GeorgiaCyber/kinetic-pillar/issues/2
