### ISSUE TITLE
[FEATURE] cloud-init supported Kali image

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [GeorgiaCyber/kinetic#20]
**Is your feature request related to a problem? Please describe.**
Need a cloud-init kali image

**Describe the solution you'd like**
This image is needed to support the GTA training requirements.

**Describe alternatives you've considered**

**Additional context**

**Comment by bitskri3g** [comment]
Closing this - applies to pillar, not core:

https://github.com/GeorgiaCyber/kinetic-pillar/issues/2
