### ISSUE TITLE
[BUG] **Windows 10 LTSC 2019 BSOD **

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [GeorgiaCyber/kinetic#21]
**Describe the bug**
Windows 10 LTSC 2019 image boots to BSOD

**To Reproduce**
launch Windows 10 LTSC 2019 instance

**Expected behavior**
Windows 10 LTSC 2019 should boot normally and allow access to OS

**Screenshots**

**Client Configuration (please complete the following information):**
 - OS: [Windows 10 LTSC 2019]
 - Interface: [Horizon,]
   - Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**

**Comment by bitskri3g** [comment]
Resolved by e650768cff1e3f4d93f17b133f407c16f8dac940

kvm.conf was not being loaded since the kvm kernel module was already active once that file was written.  Final reboot after configuration resolves this and related issues.
