### ISSUE TITLE
[FEATURE]Windows Server 2016/2019 GUI

### ISSUE THREAD

**Issue by GA-CyberWorkforceAcademy** [GeorgiaCyber/kinetic#22]
**Is your feature request related to a problem? Please describe.**
We are required to provide an environment to train on Windows Server 2016/2019 with a GUI front-end.  We require this capability in order to meet training objectives that are directly related to performing tasks on through the GUI interface for server management.

**Describe the solution you'd like**
Images available for Windows Server 2016 and 2019 with the GUI front end ready to deploy on the range.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by bitskri3g** [comment]
Closing this - applies to pillar, not core.

https://github.com/GeorgiaCyber/kinetic-pillar/issues/2
