### ISSUE TITLE
[BUG] ** salt 3000 ships with broken mysql module **

### ISSUE THREAD

**Issue by bitskri3g** [GeorgiaCyber/kinetic#51]
**Describe the bug**

ref: https://github.com/saltstack/salt/issues/56124

There are argument issues when using unix sockets on salt 3000.

**Comment by jeffdyke** [comment]
I have left comments about a work around that did well for me.  Also its worth noting that 10.4 installs with socket only access by default as part of their security updates.

**Comment by bitskri3g** [comment]
Looks good - thank you!
